@hostname = localhost
@port = 8081
@host = {{hostname}}:{{port}}
@contentType = application/json
@createdAt = {{$datetime iso8601}}

###

@name = user

POST   http://{{host}}/{{name}}/add HTTP/1.1
# DELETE http://{{host}}/{{name}}/4 HTTP/1.1